#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1575202883

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'time_sec', class 'altera_avalon_pio'
 * The macros are prefixed with 'TIME_SEC_'.
 * The prefix is the slave descriptor.
 */
#define TIME_SEC_COMPONENT_TYPE altera_avalon_pio
#define TIME_SEC_COMPONENT_NAME time_sec
#define TIME_SEC_BASE 0x40000
#define TIME_SEC_SPAN 16
#define TIME_SEC_END 0x4000f
#define TIME_SEC_BIT_CLEARING_EDGE_REGISTER 0
#define TIME_SEC_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TIME_SEC_CAPTURE 0
#define TIME_SEC_DATA_WIDTH 32
#define TIME_SEC_DO_TEST_BENCH_WIRING 0
#define TIME_SEC_DRIVEN_SIM_VALUE 0
#define TIME_SEC_EDGE_TYPE NONE
#define TIME_SEC_FREQ 50000000
#define TIME_SEC_HAS_IN 0
#define TIME_SEC_HAS_OUT 1
#define TIME_SEC_HAS_TRI 0
#define TIME_SEC_IRQ_TYPE NONE
#define TIME_SEC_RESET_VALUE 0

/*
 * Macros for device 'lp_l', class 'altera_avalon_pio'
 * The macros are prefixed with 'LP_L_'.
 * The prefix is the slave descriptor.
 */
#define LP_L_COMPONENT_TYPE altera_avalon_pio
#define LP_L_COMPONENT_NAME lp_l
#define LP_L_BASE 0x50000
#define LP_L_SPAN 16
#define LP_L_END 0x5000f
#define LP_L_BIT_CLEARING_EDGE_REGISTER 0
#define LP_L_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LP_L_CAPTURE 0
#define LP_L_DATA_WIDTH 32
#define LP_L_DO_TEST_BENCH_WIRING 0
#define LP_L_DRIVEN_SIM_VALUE 0
#define LP_L_EDGE_TYPE NONE
#define LP_L_FREQ 50000000
#define LP_L_HAS_IN 0
#define LP_L_HAS_OUT 1
#define LP_L_HAS_TRI 0
#define LP_L_IRQ_TYPE NONE
#define LP_L_RESET_VALUE 0

/*
 * Macros for device 'lp_r', class 'altera_avalon_pio'
 * The macros are prefixed with 'LP_R_'.
 * The prefix is the slave descriptor.
 */
#define LP_R_COMPONENT_TYPE altera_avalon_pio
#define LP_R_COMPONENT_NAME lp_r
#define LP_R_BASE 0x60000
#define LP_R_SPAN 16
#define LP_R_END 0x6000f
#define LP_R_BIT_CLEARING_EDGE_REGISTER 0
#define LP_R_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LP_R_CAPTURE 0
#define LP_R_DATA_WIDTH 32
#define LP_R_DO_TEST_BENCH_WIRING 0
#define LP_R_DRIVEN_SIM_VALUE 0
#define LP_R_EDGE_TYPE NONE
#define LP_R_FREQ 50000000
#define LP_R_HAS_IN 0
#define LP_R_HAS_OUT 1
#define LP_R_HAS_TRI 0
#define LP_R_IRQ_TYPE NONE
#define LP_R_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
